version: "3"
services:
  mongo:  # nombre del servicio mongo
    image: rumanoloko/p2gps:db
    deploy:
      replicas: 1  # número de réplicas
      resources:
        limits:
          cpus: "0.15"  # límite de CPU
          memory: 200M  # límite de memoria
      restart_policy:
        condition: on-failure  # reiniciar el contenedor en caso de error
    ports:
      - "28017:28017"  # mapeo de puertos
      - "27017:27017"
    volumes:
      - "db-data:/data/db"  # volumen persistente para datos de Mongo

  order:  # nombre del servicio order
    image: rumanoloko/p2gps:order
    depends_on:
      - mongo  # orden de inicio, mongo debe estar antes de order
    deploy:
      replicas: 1  # número de réplicas
      resources:
        limits:
          cpus: "0.3"  # límite de CPU
          memory: 500M  # límite de memoria
      restart_policy:
        condition: on-failure  # reiniciar el contenedor en caso de error
    ports:
      - "8080:8080"  # mapeo de puertos

  web:  # nombre del servicio web
    image: rumanoloko/p2gps:web
    deploy:
      replicas: 1  # número de réplicas
      resources:
        limits:
          cpus: "0.25"  # límite de CPU
          memory: 300M  # límite de memoria
      restart_policy:
        condition: on-failure  # reiniciar el contenedor en caso de error
    ports:
      - "80:8080"  # mapeo de puertos

volumes:
  db-data:  # definición del volumen persistente
