name: CI solamente 
on: 
  push: 
    branches: [ master ] 
  workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest 
    permissions: 
      contents: write 
      packages: write 

    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4 #descarga el repositorio en el ejecutor 

      - name: Set up JDK 8 
        uses: actions/setup-java@v4  
        with: 
            java-version: '8' 
            distribution: 'adopt' 
            server-id: github  
            settings-path: ${{ github.workspace }} # location for the settings.xml file 

      # Eliminar caché de Gradle si existe
      - name: Eliminar caché de Gradle si existe
        run: rm -rf ~/.gradle/wrapper/dists/gradle-2.1-bin/

      #### Reintentar descarga de Gradle 2.1 si es necesario ####
      - name: Reintentar descarga de Gradle 2.1
        run: |
          retries=3
          for i in $(seq 1 $retries); do
            echo "Intentando descarga de Gradle 2.1, intento #$i"
            wget -q https://services.gradle.org/distributions/gradle-2.1-bin.zip -O ~/.gradle/wrapper/dists/gradle-2.1-bin.zip && break || sleep 5
          done
          unzip -o ~/.gradle/wrapper/dists/gradle-2.1-bin.zip -d ~/.gradle/wrapper/dists/gradle-2.1-bin

      #### BUILDS ###### 
      - uses: gradle/actions/setup-gradle@v3 
        with: 
          gradle-version: 2.1  

      - name: build del Front 
        working-directory: src/Clients 
        run: ./gradlew build  

      - uses: actions/upload-artifact@v4 #guardar en Artifacts de la Acción el resultado del build. No hace falta, es por curiosidad. 
        with: 
           name: Clients 
           path: src/Clients/build/libs 

      - name: build del Back 
        working-directory: src/Backend/OrderService 
        run: ./gradlew build test
   
      - name: build del Back 
        working-directory: src/Backend/OrderService 
        run: ./gradlew build test 
